function event = parseEvent(eventname)

eventMap = struct( ...
    'cpon', 'CPOn', ...
    'cpin', 'CPIn', ...
    'sideon', 'SideOn', ...
    'sideoff', 'SideOff', ...
    'reward', 'Reward', ...
    'optout', 'OptOut');

key = lower(eventname);
if isfield(eventMap, key)
    event = eventMap.(key);
end


end